spring:
  profiles:
    active: dev
    include:
      - database
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8881
  servlet:
    context-path: /
logging:
  level:
    root: debug

---
spring:
  profiles: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /


